version: '3.3'
services:
  orai:
    image: orai/orai:alpine
    working_dir: /workspace
    tty: true
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    ports:
      - 1317:1317
      - 40000:40000
      - 26656:26656
      - 26657:26657
    security_opt:
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    env_file:
      - orai.dev.env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workspace
      - ./fn_dev.sh:/usr/local/bin/fn
    #command:
    # - bash -c "fn init && fn createValidator && fn start"
