# Working directory
# . or absolute path, please note that the directories following must be under root
root = "." 
# Optional! If `watch_dir` is empty, use `root`.
watch_dir = ""
tmp_dir = "tmp"

[build]
# Just plain old shell command. You could use `make` as well.
cmd = "make build-websocket"
# Binary file yields from `cmd`.
bin = "tmp/websocket"
# Customize binary.
full_bin = "./tmp/websocket run"
# This log file places in your tmp_dir.
log = "air_errors.log"
# Watch these filename extensions.
include_ext = ["go", "tpl", "tmpl", "html", "env"]
# Ignore these filename extensions or directories.
exclude_dir = ["assets", "tmp", "vendor", "node_modules"]
# There's no necessary to trigger build each time file changes if it's too frequency.
delay = 1000 # ms

[log]
# Show log time
time = false

[color]
# Customize each part's color. If no color found, use the raw app log.
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"
# app = "white"